title: "Dependency INjection"
email: wieland2@live.de
description: "Blogpost Dependency Injection"
baseurl: ""
url: "https://masilikum.github.io"
exclude: ["LICENSE", "Remarks.md"]
github_username: ["masilikum"]

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
